### ISSUE TITLE
after installation, open the web occured error

### ISSUE THREAD

**Issue by archonwang** [tobyqin/xmind2testlink#2]
error log 
@cicaday ， Thanks.

```
ValueError
ValueError: zero length field name in format

Traceback (most recent call last)
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1994, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/xmind2testlink/web/application.py", line 158, in index
return render_template('index.html', download_xml=download_xml, records=list(get_records()))
File "/opt/xmind2testlink/web/application.py", line 92, in get_records
sql = "select * from records where is_deleted<>1 order by id desc limit {}".format(int(limit))
ValueError: zero length field name in format
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

```

**Comment by ggqq** [comment]
well, you are using version python 2.6, which does not support `"{}".format`, please upgrade your python version at least to 2.7 or 3.x.

BTW, please delete the `data.db3` if you already failed to start the web, it might be a broken DB already. The application will help recreate one if it does not exist.

@archonwang

**Comment by archonwang** [comment]
@ggqq , Thanks. i will try it later.

**Comment by archonwang** [comment]
Nice work. Thanks.
